export const GET_DEPARTMENTS_RESPONSE = 'GET_DEPARTMENTS_RESPONSE';
export const GET_DEPARTMENT_RESPONSE  = 'GET_DEPARTMENT_RESPONSE';
export const ADD_NEW_DEPARTMENT_RESPONSE = 'ADD_NEW_DEPARTMENT_RESPONSE';
export const UPDATE_EXISTING_DEPARTMENT_RESPONSE = 'UPDATE_EXISTING_DEPARTMENT_RESPONSE';
export const DELETE_DEPARTMENT_RESPONSE = 'DELETE_DEPARTMENT_RESPONSE';

export const GET_EMPLOYEES_RESPONSE = 'GET_EMPLOYEES_RESPONSE';
export const GET_EMPLOYEE_RESPONSE  = 'GET_EMPLOYEE_RESPONSE';
export const ADD_NEW_EMPLOYEE_RESPONSE = 'ADD_NEW_EMPLOYEE_RESPONSE';
export const UPDATE_EXISTING_EMPLOYEE_RESPONSE = 'UPDATE_EXISTING_EMPLOYEE_RESPONSE';
export const DELETE_EMPLOYEE_RESPONSE = 'DELETE_EMPLOYEE_RESPONSE';

export const API_CALL_BEGIN = 'API_CALL_BEGIN';
export const API_CALL_ERROR = 'API_CALL_ERROR';
